const List = require('./list')
const Item = require('./item')
const MainList = require('./mainlist')
const Database = require('./database')

  const milk = new Item ('Milk', 2)
  const butter = new Item ('Butter', 1)
  const food = new List("Food")
  const ikea = new List("Ikea")
  const table = new Item('Table',1)
  const UliThomas = new MainList('Uli & Thomas')

  food.addItem(milk)
  food.addItem(butter)
  ikea.addItem(table)
  food.report()
  ikea.report()
  UliThomas.addList(ikea)
  UliThomas.addList(food)
  UliThomas.report()

  console.log(milk, butter, table)
  console.log(food,ikea)
  UliThomas.report()

  Database.save(UliThomas)
  const loadedFile = Database.load()
  console.log(loadedFile.items)
