const List = require('./list')
const Item = require('./item')
const MainList = require('./mainlist')
const Database = require('./database')

  const milk = new Item ('Milk', 2)
  const butter = new Item ('Butter', 1)
  const food = new List("Food")
  const ikea = new List("Ikea")
  const table = new Item('Table',1)
  const UliThomas = new MainList('Uli & Thomas')

  milk.addToList(food)
  butter.addToList(food)
  table.addToList(ikea)
  food.report()
  ikea.report()
  ikea.addToMainList(UliThomas)
  food.addToMainList(UliThomas)
  UliThomas.report()

  console.log(milk, butter, table)
  console.log(food,ikea)
  console.log(UliThomas)

  Database.save(UliThomas)
  const loadedFile = Database.load()
  console.log(loadedFile.items)
